import type { ChecklistCategory, ChecklistItem, Domain } from "../types/checklist";
import { createItemMethod } from "./playbookStrategies";
import { extendedContentCorrections } from "./extendedContentReview";

type Correction = Partial<ChecklistItem>;
const outcome = (vulnerable: string, safe: string): Correction => ({ expectedResponse: { vulnerable, safe } });
const examples = (...pairs: [string, string][]): Correction => ({ payloads: pairs.map(p => p[0]), payloadNotes: pairs.map(p => p[1]) });
const resilience = outcome("Record any missing/bypassed resilience control as a hardening observation. A vulnerability requires a separately demonstrated unauthorized operation or disclosure under the documented attacker privileges.", "The observed control resists the specific attempt. Failed tools, crashes and opaque code do not establish security of the application.");
const secret = outcome("A candidate is confirmed as non-public secret material used on a reachable path and grants unauthorized access to an owned test resource. Public API identifiers, URLs and dead/test values alone are not secrets.", "No exploitable secret was confirmed in the inspected artifacts and paths. Pattern searches can miss encoded or dynamically derived material.");
const pinning: Correction = {
  how: "Map the client's TLS stacks and pinning configuration. Record a valid-server baseline, then compare untrusted-issuer and wrong-host certificates on the unmodified release build. If pinning prevents later API testing, instrument a disposable copy separately and label that run as test setup, not a vulnerability.",
  ...outcome("The unmodified app accepts an invalid server chain/hostname and transmits a synthetic secret, or a documented pinning requirement is bypassed without modifying the trusted client environment.", "The unmodified app rejects invalid certificates while the valid-server control works. Hooking/trusting a proxy CA can legitimately make traffic visible and does not contradict this result."),
  ...examples(["frida --version", "Record the installed CLI version. Modern frida-tools resumes spawned processes by default; use its documented pause option only when needed."], ["frida-ps -Uai", "List applications on the authorized device. Any bypass script must be supplied and reviewed for the exact client stack; no universal script is included here."]),
};
const biometric: Correction = {
  how: "Identify the concrete application callback and the protected operation (not merely the unlocked screen). Compare successful, cancelled and failed biometric attempts. In a disposable instrumented build change only the application-level success decision, then attempt the protected decrypt/sign operation; compare against a genuine authentication. Record key authentication policy and server verification where present.",
  ...examples(["// Schematic: locate the application's concrete callback subclass and overload, then instrument its success decision in a disposable build. No universal callback hook is supplied.", "A hook on an empty framework base callback, or a hook that only calls the original success callback, does not manufacture biometric authentication."]),
  ...outcome("A sensitive operation that policy requires fresh user authentication to authorize succeeds after a forced UI result without a genuine authenticated key operation. Document the required instrumentation privileges.", "The protected decrypt/sign operation remains denied without actual user authentication; successful UI navigation alone does not demonstrate access. A crash is inconclusive."),
};
const backend: Correction = {
  how: "Capture one read-only backend request using test account A and replay it unchanged. Create a synthetic private object with test account B. Change only the object identifier in A's request to B's object, retaining A's session; compare against B's authorized request and an invalid-object control. Inspect the returned synthetic marker, not just HTTP status. Select separate context-specific injection checks only if a relevant sink is established.",
  ...examples(["// In the native proxy/client: replay captured GET for A's object; substitute B's test object ID while retaining A's credential.", "Use only two tester-owned objects; this is a request-editing procedure, not a universal endpoint or shell command."]),
  ...outcome("A's session reads B's private synthetic marker despite lacking access to B's object.", "B's object is denied to A while A's own object and B's authorized control succeed. Only this endpoint and role combination were tested."),
};

/** Corrections are keyed by stable item IDs; they are the authoritative shipped content. */
export const contentCorrections: Record<string, Correction> = {
  "android-static-1": { ...resilience, how: "Hash the release APK, decode resources with apktool and inspect DEX with JADX. Read the full manifest and follow exported components/debug configuration to reachable handlers. Readable source is expected; record component names and security checks before testing external access." },
  "android-static-2": secret,
  "android-static-3": outcome("A separate unprivileged app invokes a sensitive exported activity and obtains a protected result without the required caller/session authorization. Exported status alone is only a lead.", "The sensitive operation enforces caller/session permissions; ordinary launcher or share activities may legitimately be exported."),
  "android-static-4": { ...outcome("The production artifact is debuggable and the documented attacker with authorized ADB/device access can reach a sensitive diagnostic capability. Report build configuration separately from demonstrated data access.", "The production manifest disables debugging and run-as is denied in the tested environment; this does not establish overall app security."), ...examples(["apkanalyzer manifest print app.apk", "Read the release manifest's effective debuggable attribute."], ["adb shell run-as com.example.app id", "Replace the example package; requires authorized ADB. run-as normally requires a debuggable installed app, not merely a rooted device."]) },
  "android-static-5": { how: "Inspect allowBackup, fullBackupContent and dataExtractionRules with OS/target SDK recorded. Test cloud/device-transfer rules separately from legacy adb backup. On Android 12+ with targetSdk 31+, adb backup excludes non-debuggable app data; OEM device-transfer behavior can differ. Use synthetic data and prove what a restore exposes.", ...outcome("A supported backup/restore route exposes a protected synthetic marker to an actor outside the intended policy; a non-empty archive alone is insufficient.", "The tested backup route excludes or appropriately protects the marker. A failed legacy adb backup says nothing about cloud or device-transfer backups."), ...examples(["apkanalyzer manifest print app.apk", "Resolve fullBackupContent/dataExtractionRules resources and inspect include/exclude rules for each supported transport."]) },
  "android-static-8": outcome("Attacker-controlled content can reach an annotated sensitive bridge method and produce unauthorized access or an action using the test fixture.", "Untrusted content cannot reach sensitive bridge operations. Merely enumerating a bridge object or enabling JavaScript is not a vulnerability."),
  "android-static-9": { how: "Trace SecretKeySpec/IvParameterSpec or GCMParameterSpec from initialization to the actual cipher. Distinguish key material from public IVs and unused constants. Verify a candidate static key decrypts a synthetic protected artifact; evaluate IV/nonce reuse against the specific mode, not as a secret-exposure claim.", ...secret },
  "android-static-10": resilience,
  "android-static-11": outcome("The exact bundled library version/build is affected, and the vulnerable functionality is reachable with attacker-controlled input in this app's configuration.", "No reachable affected path was confirmed in the inspected dependency inventory. Version strings can be missing or backported; current versions do not prove absence of flaws."),
  "android-static-12": outcome("A reachable production flow actually transmits a synthetic secret over cleartext, with the effective network security policy recorded.", "No sensitive cleartext was observed in tested flows. A permissive flag alone is a configuration lead, not observed disclosure."),
  "android-dynamic-1": pinning,
  "android-dynamic-2": resilience,
  "android-dynamic-3": { how: "Trace only the exact logging/crypto API overload reached by a synthetic feature operation; record signatures and preserve original return values. Compare with an uninstrumented run. Follow any marker beyond normal in-process crypto arguments to an unintended log, exported component or recipient.", ...outcome("A synthetic secret reaches an unintended recipient or log accessible under the documented threat model, confirmed without the analysis hook creating the disclosure.", "No unintended sink receives the marker on tested paths. Plaintext passed to encryption or returned by decryption inside the process is normal."), ...examples(["frida-trace -U -f com.example.app -j 'javax.crypto.Cipher!doFinal' -j 'android.util.Log!*'", "Frida Java include syntax is Class!method. Replace the package and inspect generated handlers; tracing alone does not dump every argument or prove a leak."]) },
  "android-dynamic-4": { how: "Locate the exported activity and read its required Intent extras. Run its legitimate flow, then launch it logged out via ADB as discovery. Reproduce from a separately signed unprivileged fixture app and attempt one protected read/action. ADB shell UID is not equivalent to an arbitrary app.", ...outcome("The unprivileged caller obtains the protected result without required authorization, not just a screen launch.", "The protected operation is denied to the unprivileged caller while legitimate access works.") },
  "android-dynamic-7": { how: "Copy a synthetic marker using the feature; record Android/API and foreground/default-IME access conditions. Observe the Android 13+ clipboard preview, then test reading from a separate foreground test app where platform rules allow it. Test expiration and clearing separately. dumpsys output and instrumentation are not an arbitrary background-app capability.", ...outcome("An unintended permitted reader obtains a sensitive marker or the visual preview exposes it contrary to the product policy; document user interaction and OS restrictions.", "The tested exposure is prevented. EXTRA_IS_SENSITIVE masks the preview only: it does not encrypt the clipboard or prevent all permitted apps reading it."), ...examples(["// Android 13+ preview control: ClipDescription.EXTRA_IS_SENSITIVE = true in ClipDescription extras", "Schematic configuration reference. Compare masked/unmasked preview separately from clipboard read access; background reads have been restricted since Android 10."]) },
  "android-dynamic-8": biometric,
  "android-storage-1": { ...examples(["adb shell run-as com.example.app sh -c 'cat shared_prefs/*.xml'", "Run only on your debuggable fixture; the shell expands the glob under the app UID. For a release build use an authorized acquisition method and record its privileges."]) },
  "android-storage-2": { how: "Write a synthetic file through the app, locate its actual storage path and inspect access from another unprivileged app on the recorded OS/target SDK. Distinguish public shared storage from app-specific external directories and scoped-storage exemptions.", ...outcome("A second app without the intended grant can read the sensitive marker under the tested platform's effective storage rules.", "The marker is inaccessible to the tested caller. ADB/root reads and a /sdcard path alone do not show cross-app access.") },
  "android-storage-3": { how: "Trace key generation and use. Inspect KeyInfo security level (API-dependent) and authentication policy; AndroidKeyStore provider selection alone does not prove TEE/StrongBox backing. Assess exportability and access against the actual threat model.", ...outcome("A protected key is recoverable or usable by an unauthorized actor under the intended device state; document the exact extraction/use path.", "The tested key access policy is enforced. Grep matches or no raw key filenames do not establish hardware backing.") },
  "android-storage-4": { how: "Inspect the app's supported backup/restore rules and create an approved synthetic backup. Record format version, compression/encryption and OS/target SDK. Parse with a format-aware tool and compare restored marker accessibility; never assume a fixed 24-byte header.", ...examples(["apkanalyzer manifest print app.apk", "Resolve dataExtractionRules/fullBackupContent and inspect the relevant backup transport before acquiring data."]), ...outcome("The supported backup/restore path exposes the synthetic secret outside the intended policy.", "The tested backup protects/excludes the marker; empty archives, parse failures and obsolete adb backup commands are inconclusive.") },
  "android-storage-5": { how: "With documented acquisition privileges copy the actual WebView storage and any SQLite WAL/SHM companions after a synthetic login. Inspect schema with a desktop read-only viewer before querying marker-bearing fields; filenames/schema and encrypted_value usage vary. Compare after logout and test whether the marker is exposed outside the intended app sandbox.", ...examples(["sqlite3 -readonly copied-cookies.db '.schema'", "A desktop command against a consistent acquired copy, not an assumption that sqlite3 exists on the device. Query only synthetic marker records after inspecting schema."]), ...outcome("The synthetic authenticated marker remains accessible to an unintended actor or beyond a documented logout/retention boundary.", "No such access was demonstrated. In-sandbox session cookies are expected and a plaintext cookie field alone does not prove cross-app access.") },
  "android-crypto-1": { how: "Trace the sensitive key's generation, persistence and use, inspect KeyInfo security level and authentication policy on the actual device, and compare authorized and denied key operations. AndroidKeyStore may be software- or hardware-backed depending on device/key parameters.", ...outcome("The key is recoverable or usable by an unauthorized actor under the documented policy.", "The recorded key policy denies the unauthorized operation; provider names alone do not prove hardware protection.") },
  "android-crypto-3": { text: "Check AES IV/nonce requirements and reuse under the same key", how: "Identify the exact mode and key identifier. Capture IV/nonce values for two synthetic encryptions without recording production keys. For GCM require unique nonces under a key; for CBC require unpredictable IVs. Reusing an AES key for multiple messages is normal when mode-specific constraints hold.", ...outcome("GCM repeats a nonce under the same key or CBC uses a fixed/predictable IV on the relevant security-sensitive path; show the concrete confidentiality/integrity effect.", "The mode-specific IV/nonce requirement holds for the observed operations. Key reuse alone is not a flaw.") },
  "android-crypto-2": outcome("A deprecated primitive or insecure mode is used on a reachable security-sensitive path with a demonstrated relevant weakness; non-security checksums do not count.", "The tested path uses appropriate modern cryptography, including integrity/authentication where needed. AES-CBC with a random IV alone does not provide ciphertext authenticity."),
  "android-crypto-5": pinning,
  "android-crypto-6": { ...examples(["// Local fixture: preserve a valid CBC ciphertext, change one byte in the previous block, compare padding-invalid and authentication-invalid controls.", "Schematic bounded oracle test; use valid ciphertext from the fixture. A literal ellipsis is not hex, and one noisy timing difference is not an oracle."]), how: "Identify CBC/padding and the observable error boundary first. In a local fixture compare a valid ciphertext with bounded byte changes and equal-length negative controls. Repeat in alternating order; distinguish a stable padding-validity oracle from generic corruption, authentication failure and timing noise." },
  "android-network-1": pinning,
  "android-network-4": backend,
  "android-network-5": { how: "Connect only the test device to a controlled access point. Establish a valid TLS baseline, then route the app to a test server presenting an untrusted or wrong-host certificate without installing its CA. Confirm whether a synthetic secret is actually sent. An app need not reject a Wi-Fi network if TLS remains valid.", ...examples(["// Device Settings: record the current proxy, configure the controlled test proxy, and restore the recorded value after testing.", "Use an isolated network; no spoofed public SSID or third-party clients are needed."]), ...outcome("The unmodified client sends a secret after accepting an invalid certificate or over plaintext.", "The invalid connection is rejected and the valid control works. Normal encrypted traffic over an untrusted Wi-Fi network is not a flaw.") },
  "android-ipc-3": { how: "Distinguish started services from bound Binder/AIDL services. Read the manifest and interface, exercise a valid call, then use a separate unprivileged test app to start or bind as appropriate and invoke one non-destructive operation. Inspect caller UID/permission checks at the actual sensitive method.", ...examples(["adb shell am startservice -n com.example.app/.ExampleService", "Discovery only for started services. This does not perform Binder binding; a version-matched fixture app is needed for AIDL/Messenger tests."]) },
  "android-ipc-5": { how: "Locate getParcelableExtra followed by a launch/forward operation. Build a separate unprivileged Android fixture app that puts a real nested Intent Parcelable under the observed extra key, targeting a harmless protected fixture component. Compare direct denial with indirect forwarding and a permitted destination control.", ...examples(["// Schematic Kotlin fixture:\nval nested = Intent().setComponent(ComponentName(targetPackage, privateActivity))\nval outer = Intent().setComponent(ComponentName(targetPackage, exportedActivity))\nouter.putExtra(observedExtraKey, nested)\nstartActivity(outer)", "Run inside a test Activity after defining names from the actual manifest/source. ADB --es/-e sends a string, not a nested Intent Parcelable."]) },
  "android-ipc-6": { how: "Trace PendingIntent creation flags, explicit component and how an untrusted recipient obtains the token. In a fixture app that legitimately receives it, vary one allowed fill-in field and observe the privileged action, compared with an immutable or fully specified control. Mutability can be legitimate for features such as inline replies." },
  "android-reverse-1": resilience, "android-reverse-2": resilience, "android-reverse-3": resilience, "android-reverse-4": resilience, "android-reverse-5": { ...resilience, ...secret },
  "android-flutter-1": { ...secret, how: "Extract libapp.so and libflutter.so from the same APK/ABI; use a blutter version supporting that Dart snapshot. Trace recovered strings/offsets to a reachable consumer. Analysis output is reconstructed, not original source. reFlutter is separate instrumentation and successful proxying is not a flaw." },
  "android-hermes-1": { ...secret, how: "Extract assets/index.android.bundle, identify its Hermes bytecode version and use a compatible disassembler. Inspect strings and bytecode consumers for non-public secrets; HASM is disassembly, not necessarily recovered original JavaScript." },
  "android-bio-bypass-1": biometric,
  "android-applink-1": { how: "Compare assetlinks.json package/certificate fingerprints to the release signer and inspect pm get-app-links on the test device. Open the link from a browser without forcing a package and record actual OS routing. Separately test the handler's token/session validation with valid and invalid synthetic tokens. On Android 12+ unverified web links generally open in the browser.", ...outcome("An actual misbinding delivers a synthetic credential to an unintended receiver, or the legitimate handler performs an unauthorized operation with invalid input.", "Routing and handler authorization hold in the tested OS/configuration. Missing assetlinks.json alone does not prove token interception."), ...examples(["adb shell pm get-app-links com.example.app", "Record OS version and release signer; replace package."], ["adb shell am start -a android.intent.action.VIEW -d 'https://example.com/reset?token=test-marker'", "Replace with an owned domain and synthetic token. Do not force the package when testing OS link routing."]) },
  "ios-static-1": secret, "ios-static-3": secret,
  "ios-static-7": outcome("The exact bundled version is affected and the vulnerable feature is reachable under this app's configuration and attacker input.", "No reachable affected path was confirmed in the inspected framework inventory; version matching or lack of CVE hits is not conclusive."),
  "ios-static-2": outcome("A reachable sensitive flow uses cleartext/weak transport permitted by an ATS exception; record the effective domain-specific configuration and actual traffic.", "The tested flow enforces valid TLS. ATS and certificate pinning are different controls; an ATS exception alone is not data disclosure."),
  "ios-dynamic-1": pinning, "ios-network-1": pinning,
  "ios-dynamic-2": { how: "Read the real registered scheme and handler parameters. Open a valid synthetic link, then change one parameter to an invalid marker of the same type. Compare logged-out/logged-in handling and the actual protected result. Only try SQL/JavaScript syntax if tracing establishes that exact sink; do not default to a destructive action.", ...examples(["xcrun simctl openurl booted 'myapp://fixture?marker=baseline'", "Schematic URI: replace with the observed harmless handler and compare marker=invalid. Device routing/entitlements can differ from the simulator."]) },
  "ios-dynamic-3": { ...examples(["// In a controlled debugger/harness: locate a unique synthetic secret buffer during use, after operation completion, and after logout; record address/range and acquisition privileges.", "Do not search only for the word password or one memory protection range. Normal in-use plaintext is expected; quantify avoidable lifetime and attacker access."]), ...outcome("A synthetic secret persists beyond the documented lifetime and is recoverable by an actor within the stated threat model, not only the instrumented owning process.", "No excess lifetime/exposure was confirmed in sampled ranges and states; missing matches do not prove all buffers were cleared.") },
  "ios-dynamic-4": { how: "Place only a synthetic marker on the general pasteboard through the app. On the recorded iOS version test reading from a separate app, noting foreground state, user paste action and OS consent prompt. Compare expiration/localOnly settings and a non-sensitive control.", ...outcome("An unintended reader obtains the marker under the recorded user/OS access conditions, or sensitive data persists beyond its intended lifetime.", "The tested pasteboard exposure is prevented. Instrumented in-process reads do not bypass iOS cross-app paste permission requirements.") },
  "ios-dynamic-5": biometric, "ios-dynamic-7": backend,
  "ios-storage-1": { how: "Compare Keychain storage with NSUserDefaults/plist storage using synthetic credentials. Inspect Keychain accessibility, access group, synchronizable and access-control attributes; test permitted and denied lock/authentication states. A Keychain API or instrumentation dump returns decrypted values by design and is not a raw disk-encryption test.", ...outcome("Sensitive credentials are placed in an unintended plist/store or are accessible through an overly permissive Keychain policy under the documented unauthorized actor/state.", "The tested Keychain/file policy blocks the unauthorized read. Decrypted output obtained by the authorized app is not evidence of plaintext Keychain storage on disk.") },
  "ios-storage-2": { how: "Inspect each sensitive item's kSecAttrAccessible, kSecAttrSynchronizable, access group and SecAccessControl flags. Compare access before first unlock, after first unlock while locked, and when unlocked as required by the feature. ThisDeviceOnly affects migration; it is not the iCloud synchronizable flag.", ...outcome("A synthetic sensitive item is readable in a lock/authentication state disallowed by the intended policy.", "The tested accessibility/access-control policy matches the feature. AfterFirstUnlock may be required for background use; lack of ThisDeviceOnly is not automatically a vulnerability.") },
  "ios-storage-4": { ...examples(["idevicebackup2 backup --full ./backup", "Creates a backup honoring the device's configured encryption state; it does not guarantee an unencrypted backup. Use only the authorized test device."], ["// Inspect NSURLIsExcludedFromBackupKey on each synthetic sensitive file and compare an actual restored backup.", "API-name grep is a lead; runtime attributes and the supported backup route determine behavior."]) },
  "ios-storage-5": { ...examples(["// Acquire the fixture app's actual Library/WebKit files with documented privileges, including database companions; identify each format before inspection.", "Paths/table names vary by OS and WebKit. Do not assume WebsiteData.db contains ItemTable."], ["sqlite3 -readonly acquired-webkit.db '.schema'", "For an actual SQLite working copy only; query the synthetic marker after inspecting the schema. Compare before and after logout."]) },
  "ios-network-4": { how: "Establish a valid-server baseline on the unmodified app, then use a controlled endpoint/proxy with a certificate whose issuer is not trusted by the device and separately a wrong-host certificate. Keep the CA out of the trust store and disable all hooks. Inspect URLSession challenge handling and confirm actual request success or certificate rejection.", ...examples(["// Controlled TLS endpoint: serve an untrusted-issuer certificate; repeat separately with a trusted but wrong-host certificate.", "Server-side fixture setup is required. openssl s_client -cert presents a client certificate and does not test an iOS app's server-certificate validation."]) },
  "ios-crypto-3": { how: "On the actual device inspect NSFileProtectionKey for the sensitive file and test access after close/lock versus unlocked baseline. Account for inherited/default protection and open file handles; absence of an API string does not mean protection is disabled.", ...outcome("A file is accessible in a state where the documented protection policy requires denial, with acquisition privileges and open handles recorded.", "The tested file's effective protection and lock-state access meet policy. API imports alone do not establish this."), ...examples(["// In an authorized app test harness: read FileManager attributesOfItem(atPath:) and inspect .protectionKey for the exact synthetic file.", "Schematic API procedure: use the file created by the real feature; verify on device, since simulator behavior is not equivalent."]) },
  "ios-crypto-4": { how: "Trace the actual token/nonce generation call path. Distinguish rand/srand and weak seeds from SecRandomCopyBytes or the platform arc4random CSPRNG. Check output length, bias and nonce requirements; predict a future synthetic value from attacker-observable information before claiming predictability.", ...examples(["nm -u Payload/App.app/App | grep -E '_(rand|srand|arc4random|SecRandomCopyBytes)'", "Imports are leads, not call-path proof. Apple's arc4random family is cryptographically secure; rand/srand is not appropriate for security tokens."]), ...outcome("A security token uses a predictable PRNG/seed and the attacker can predict an unobserved synthetic value under realistic knowledge.", "The relevant path uses a suitable CSPRNG such as SecRandomCopyBytes or arc4random with adequate entropy; presence of rand elsewhere is not a flaw.") },
  "ios-jailbreak-1": resilience, "ios-jailbreak-2": { ...resilience, ...examples(["nm -u Payload/App.app/App | grep ptrace", "Read-only lead. A version/ABI-specific instrumentation test must preserve unrelated ptrace operations; replacing all calls with zero is not a valid general hook."]) }, "ios-jailbreak-3": resilience, "ios-jailbreak-4": resilience,
  "ios-ulink-1": outcome("A controlled invalid link causes unauthorized account/state change or a proven association misbinding leaks a synthetic credential.", "The observed association and handler validation enforce the intended boundary. Wildcard AASA paths can be legitimate and do not themselves prove a flaw."),
  "ios-appgroup-1": { how: "Read signed entitlements, enumerate the app-group members and inspect synthetic shared files under their effective access. Compare an entitled extension with a separate non-entitled app; define whether compromise of the extension is in the threat model.", ...examples(["codesign -d --entitlements :- Payload/App.app", "Inspect the signed com.apple.security.application-groups entitlement rather than assuming Info.plist declares it."]), ...outcome("A principal outside the intended sharing boundary reads a sensitive marker, or a less-trusted entitled extension violates the documented data-minimization policy.", "Only intended group members can read required shared data. Sharing with an entitled extension is expected, not arbitrary cross-app disclosure.") },
  "tc-static-1": secret, "tc-java-1": secret,
  "tc-static-3": { ...secret, how: "Trace candidate embedded symmetric/private key material to a live decrypt/sign consumer and test one synthetic artifact. Public RSA keys and IVs are not secrets; IV weaknesses depend on cipher mode. Do not conclude every locally encrypted record can be decrypted from a string match." },
  "tc-static-5": outcome("The actual updater accepts and applies a tampered or wrong-publisher fixture update without its intended integrity/authorization check.", "The updater rejects invalid fixture updates while accepting a legitimate one. It need not invoke the signtool CLI; equivalent in-process signature or authenticated metadata validation can be correct."),
  "tc-dynamic-1": { how: "Record the process identity and the privileges needed to acquire memory. Use a unique synthetic credential, compare memory during legitimate use, after completion and after logout. Quantify unnecessary retention and whether a realistic unauthorized reader can recover it; normal in-use plaintext is expected.", ...outcome("A protected synthetic secret persists beyond policy and an actor inside the threat model can recover/use it without already controlling the authorized process.", "No excess exposure was confirmed in the tested ranges and lifecycle; a strings search is incomplete and cannot prove universal zeroization.") },
  "tc-static-6": { ...examples(["dumpbin /imports MyApp.exe", "Static imported-library inventory; not a proof of actual load order."], ["// Process Monitor: filter the real process for Load Image and file lookup events; inspect effective ACLs at the resolved paths.", "A missing lookup alone is not execution. No unrelated credential-recovery package is needed."]) },
  "tc-dynamic-5": resilience, "tc-dynamic-6": resilience, "tc-binary-5": resilience,
  "tc-binary-4": { how: "Identify the actual serializer, reachable input and runtime/library versions. First test a benign unexpected type against a valid serialized fixture. Only in a disposable VM use a version-compatible gadget producing a harmless local marker; compare a blocked-type control and preserve the execution trace.", ...examples(["// Schematic: valid fixture -> same format with one unexpected type -> version-matched harmless marker gadget in the isolated VM.", "There is no universal ysoserial syntax across Java, .NET and Hessian tools. Pin the actual tool/release and generator before running a payload."]) },
  "tc-network-1": pinning, "tc-network-5": backend,
  "tc-network-3": { ...examples(["tcpdump -i any -w login.pcap host 192.0.2.10", "Linux example: replace the documentation address with the isolated fixture host; record the actual interface. Capture all ports because port 443 is not proof of TLS and TLS can use other ports."], ["tshark -r login.pcap -Y 'tcp'", "Reassemble the actual auth stream in Wireshark and look for a synthetic credential; encrypted or incomplete packets limit visibility."]) },
  "tc-network-4": { ...examples(["mitmproxy --listen-host 127.0.0.1 -p 8080", "Route the disposable client to this controlled proxy without trusting its CA; test the certificate presented to the client, not Burp's upstream validation."], ["// Repeat with a wrong-host certificate on a controlled endpoint while retaining the valid-certificate baseline.", "Keep trust-store and hook state fixed between runs."]) },
  "tc-electron-5": { how: "Inspect effective webPreferences for the actual renderer. From controlled untrusted content attempt to read a synthetic resource on a different owned origin that intentionally sends no CORS permission. Compare with an ordinary browser and the valid same-origin control; inspect actual response access.", ...outcome("The renderer reads a resource across a forbidden origin boundary due to disabled webSecurity, from an attacker-reachable content path.", "The cross-origin read is denied and permitted controls work. A server intentionally allowing CORS is not a bypass.") },
  "tc-electron-6": { ...examples(["// In an authorized main-process debugging context: process.versions.electron and process.versions.chrome", "Record bundled runtime versions; the application's --version can report only the app version."], ["// Compare the exact bundled build with upstream release notes and the affected feature's reachability.", "package.json may specify a range rather than the shipped version; a scanner/CVE match needs build and configuration validation."]) },
  "tc-tauri-1": { how: "Record Tauri/plugin major versions. Inspect actual registered commands, caller-window/origin capabilities and shell scope. From the legitimately reachable renderer invoke one permitted harmless command, then change one program/argument/path outside scope. Compare with a denied origin/window and inspect the actual Rust-side effect; custom commands need their own authorization.", ...examples(["// Tauri v2 fixture: import { invoke } from '@tauri-apps/api/core'; await invoke(observedCommandName, benignObservedArguments);", "Schematic frontend code; define arguments from the app's real command schema. window.__TAURI__ depends on withGlobalTauri and private internals are not a stable API."], ["// For the installed shell plugin version, test one allowed program/argument against one outside its capability scope using its documented frontend API.", "Tauri v1 allowlist and v2 capabilities/permissions differ. A hardcoded plugin:shell internal call is not a portable reproduction."]) },
  "tc-java-3": { ...examples(["jconsole", "Use the observed service:jmx:rmi URL in the Remote Process dialog with no credentials, then compare an authorized test principal. Read only a harmless MBean attribute."], ["// Inspect com.sun.management.jmxremote.authenticate, SSL configuration and network ACLs for the actual JVM.", "An open RMI registry or unauthenticated read does not automatically permit MBean deployment or RCE."]), ...outcome("An unauthorized principal reads a protected MBean or performs a disallowed operation; report only the capability demonstrated.", "The tested protected MBean operation requires the intended authentication/authorization. Registry reachability alone is not RCE.") },
  "tc-java-4": { text: "Review legacy Java sandbox assumptions and modern process isolation", how: "Record the shipped JDK version. SecurityManager is legacy/deprecated and permanently disabled starting with JDK 24 (JEP 486); do not recommend enabling it on modern JDKs. For a supported legacy sandbox compare a denied file read with a permitted one. For modern clients inspect OS/container/service identity boundaries around untrusted code instead.", ...examples(["java -version", "Run the shipped runtime, not an unrelated system JVM."], ["// Legacy-only: inspect the effective java.security.policy and sandbox permissions. Modern JDK: inspect OS process identity and resource ACLs.", "Procedure, not a portable JVM command. Missing SecurityManager on JDK 24+ is expected."]), ...outcome("Untrusted code crosses an intended, documented legacy sandbox or modern OS boundary to read a synthetic protected resource.", "The tested boundary denies the protected operation. SecurityManager absence alone is not a vulnerability."), reference: "https://openjdk.org/jeps/486" },
  "tc-privesc-5": { how: "Enumerate the named IPC endpoint and inspect its actual DACL plus server-side impersonation/caller checks. Determine the real message framing and command schema from the legitimate client. Compare one harmless supported request from authorized and standard-user fixtures; do not assume the pipe executes shell strings.", ...examples(["PipeList.exe", "Enumerates named pipes and instance counts, not their DACLs."], ["// Inspect the selected pipe security descriptor and send a schema-valid read-only fixture request from a standard-user client.", "Use a protocol-specific harness with timeouts and dispose streams afterward; a generic whoami string is not a valid universal pipe command."]) },
  "tc-shell-open": { how: "Trace untrusted input to shell.openExternal and record OS/Electron version, scheme parser and installed handlers. In a disposable VM register a harmless custom fixture handler, then compare allowed HTTPS and denied fixture schemes from the real untrusted input. Inspect the handler launch and arguments; old ms-msdt payloads depend on historical OS vulnerabilities.", ...examples(["// Local fixture: request fixture-test://marker from the app's actual untrusted input, with a benign handler recording its argv.", "Schematic isolated-VM procedure; never assume every non-HTTPS URL executes a command."]), ...outcome("Attacker-controlled input launches a disallowed handler/action outside the application's intended URL policy.", "Parsed scheme/host policy rejects disallowed handlers while legitimate links work; prefix matching alone is not a complete policy.") },
};

/** Review notes for the retired 2,601-line Android generator (all nine categories). */
export const androidLegacyReview = {
  static: "12 item branches reviewed: four-tool duplication, grep misses treated as safe, public identifiers treated as secrets, fake CVE examples, fixed backup headers and R8 deobfuscation guarantees removed.",
  dynamic: "8 branches reviewed: obsolete spawn flag, wrong native verification return hooks, overload-free/recursive Java hooks, no-op biometric hooks, ADB string-vs-Parcelable confusion and clipboard preview/access conflation removed.",
  storage: "7 items previously ignored: removed category-wide backup/screenshots for unrelated storage checks and unqualified scoped-storage/Keystore claims.",
  crypto: "6 items previously ignored: mode-specific nonce/IV requirements replace key-reuse claims; padding tests no longer use invalid ellipsis hex or unrelated automated probes.",
  network: "5 items previously ignored: separate valid/invalid TLS controls, pinning instrumentation and backend authorization.",
  ipc: "8 items previously ignored: concrete caller UID, binding vs start, real nested Parcelable and actual protected effect required.",
  reverse: "5 items previously ignored: resilience observations are not vulnerability or clean verdicts.",
  hybrid: "Flutter and Hermes separated by item; no invented source recovery or mTLS/non-bypassability guarantees.",
  modernAuth: "Biometric callback and App Links methods no longer mixed; browser routing is tested without forcing package and OS-version assumptions recorded.",
};

export interface ContentReviewAuditRecord {
  domainId: Domain;
  categoryId: string;
  itemId: string;
  rawIssues: string[];
  effectiveIssues: string[];
  correctedFields: string[];
}
const contentReviewAudit: ContentReviewAuditRecord[] = [];
export function inspectContentIssues(item: ChecklistItem): string[] {
  const issues: string[] = [];
  if ((item.payloads?.length ?? 0) !== (item.payloadNotes?.length ?? 0)) issues.push("payload-note-count");
  if ([item.how, ...(item.payloads ?? []), ...(item.payloadNotes ?? [])].some(s => s.includes("--no-pause"))) issues.push("obsolete-frida-flag");
  if (item.payloads?.some(s => /-j\s+['"][\w.$]+\.[\w*$]+['"]/.test(s))) issues.push("frida-java-selector-needs-bang");
  return issues;
}
/**
 * Compatibility architecture: legacy catalogue literals retain stable IDs/content;
 * exact-ID overlays fix reviewed claims before exports are consumed and methods are
 * materialized. This is NOT a second live catalogue or an automatic proof of review.
 * Raw issues stay visible here even when an overlay fixes effective data. New edits
 * should update source literals first and remove redundant overlays when feasible.
 * In particular, mismatched notes are never padded/truncated to manufacture coverage.
 */
export function auditOwnedContent(): ContentReviewAuditRecord[] {
  return contentReviewAudit.map(row => ({ ...row, rawIssues: [...row.rawIssues], effectiveIssues: [...row.effectiveIssues], correctedFields: [...row.correctedFields] }));
}
export function applyContentReview(domain: Domain, categories: ChecklistCategory[]) {
  for (const category of categories) for (const item of category.items) {
    const rawIssues = inspectContentIssues(item);
    Object.assign(item, contentCorrections[item.id], extendedContentCorrections[item.id]);
    // All supplied snippets remain examples: no automatic execution or HTTP wrapping.
    // Syntax defects are repaired in source, not silently normalized here.
    if (domain === "web3") {
      item.how = `Local fixture only; no broadcast or live-chain writes. ${item.how}`;
      item.payloads = item.payloads?.map(value => value.includes("cast send") ? `// Schematic LOCAL TEST sequence; adapt the actual ABI in Foundry/Hardhat, never broadcast:\n// ${value.replaceAll("\n", "\n// ")}` : value);
    }
    const effectiveIssues = inspectContentIssues(item);
    if (item.expectedResponse) item.expectedResponse.safe = `${item.expectedResponse.safe} This is a scoped observation, not proof that the whole target is safe; tool/setup failures are inconclusive.`;
    item.methods = [createItemMethod(item, category, domain, effectiveIssues.length === 0)];
    if (effectiveIssues.length) item.methods[0].limitations?.push(`Content needs repair: ${effectiveIssues.join(", ")}. No missing note was synthesized.`);
    contentReviewAudit.push({ domainId: domain, categoryId: category.id, itemId: item.id, rawIssues, effectiveIssues, correctedFields: [...new Set([...Object.keys(contentCorrections[item.id] ?? {}), ...Object.keys(extendedContentCorrections[item.id] ?? {})])] });
  }
}
