import type { ChecklistCategory, ChecklistItem, Domain, TestingMethod } from "../types/checklist";

type Strategy = { id: string; baseline: string; variation: string; evidence: string; limitation: string; cleanup: string; tools: string[] };
const strategies: Record<string, Strategy> = {
  discovery: { id: "scoped-discovery", baseline: "Identify the owned asset and the exact discovery source/protocol named in this item. Record scope, query time and one known asset as a positive control; begin with existing/passive records where available.", variation: "Apply the specific discovery query below to a bounded scope; compare one known result and one nonexistent control. Correlate candidates with an independent authoritative source before treating them as current or owned assets.", evidence: "Exact query/source and timestamp, raw record, known/nonexistent controls, ownership and independent validation.", limitation: "Discovery is inventory, not a vulnerability. Stale records, wildcards, shared hosting, catch-all responses and version banners need confirmation. Do not substitute public DNS for directory or private-service discovery.", cleanup: "Stop collectors and remove temporary test records/listeners; retain a scoped inventory with provenance.", tools: ["The discovery source/client named in the item", "Authoritative inventory"] },
  access: { id: "identity-state-comparison", baseline: "Prepare two owned test identities/roles and synthetic private resources. Record the intended permission/session policy and capture a legitimate operation with the exact interface named below.", variation: "Repeat the same operation with only the identity, object reference, session state or workflow condition described by this item changed. Include permitted and denied controls and inspect the protected data/state rather than status code alone.", evidence: "Actor/role and session state, synthetic resource ownership, baseline/candidate/denied inputs and actual protected state or marker.", limitation: "Public/shared data, intentional delegation and client-only UI changes are false positives. A different status or response length alone is not unauthorized access.", cleanup: "Delete test objects, revoke synthetic sessions and restore roles/workflow state.", tools: ["Native application client", "Request and authorization audit trace"] },
  parser: { id: "context-specific-parser", baseline: "Trace the item's exact input to its actual parser/sink and identify grammar, encoding and engine/version. Preserve a valid input carrying a unique harmless marker and its normal result.", variation: "Change only that input using the context-specific item procedure below, then compare an inert or invalid control of the same shape. Require observable interpretation at the identified sink or a protected state change; repeat timing/error comparisons to exclude noise.", evidence: "Source-to-sink context, exact bytes/encoding, baseline and control output, engine/parser trace or synthetic marker effect.", limitation: "An error, reflection, timeout or scanner label is not proof of injection. SQL, templates, shell, XML and browser sinks have different grammars; never apply one class's payload to another by keyword.", cleanup: "Remove synthetic markers/objects and restore state; keep execution, parser crashes and outbound callbacks in controlled fixtures.", tools: ["Native input client", "Parser/runtime trace"] },
  browser: { id: "browser-origin-boundary", baseline: "Record browser/version, origins, authentication state and response policy. Establish the legitimate same-origin/user-interaction flow with synthetic data before the named cross-origin or rendering test.", variation: "Use a separate controlled origin or the exact rendering context below; vary one origin/header/message/input at a time. Compare an allowed control with a rejected control in a real browser and inspect script-visible data or the resulting protected action.", evidence: "Origin and frame context, actual response headers/input, browser console/network trace and script-visible marker or action result.", limitation: "HTTP replay alone does not reproduce browser enforcement. CORS reflection without readable protected data, framing without an actionable UI, and inert HTML reflection are not equivalent to exploitation.", cleanup: "Remove controlled pages/markers, clear test sessions and restore browser settings; do not weaken browser security flags for a proof.", tools: ["Browser DevTools", "Controlled second-origin fixture"] },
  artifact: { id: "artifact-review", baseline: "Hash the release artifact and record architecture, version, acquisition source and analysis-tool version. Inspect a read-only copy and locate the exact file, function or configuration named by this check.", variation: "Trace this candidate to its consumer and compare with a known-good configuration or reachable benign execution of that same function. Change only the relevant setting/input in a disposable copy if runtime confirmation is needed.", evidence: "Artifact hash, file/offset or source line, caller-to-sink trace, effective configuration and controlled comparison.", limitation: "Strings, imports, missing symbols, readable code and scanner matches are leads; absence of matches is not proof of absence. Hardening gaps need a threat model and reachable impact.", cleanup: "Retain hashes and redacted excerpts; remove extracted private data and disposable analysis copies per the retention policy.", tools: ["Platform decompiler / disassembler", "Read-only configuration inspection"] },
  mobile: { id: "mobile-runtime", baseline: "Record release build, device OS/API, target SDK, signing identity, account state and root/jailbreak/debug status. Exercise the named feature normally on an unmodified build using synthetic data.", variation: "Repeat that exact feature with one input or state change described below; compare the same operation with a valid control and an invalid/denied control. For cross-app access reproduce from a separate unprivileged test app, not only an ADB/root shell.", evidence: "Build hash, device state, caller UID/permissions, exact feature/input, before/after screen or artifact and the actual protected operation result.", limitation: "Instrumentation, plaintext at crypto API boundaries, successful decompilation, missing obfuscation or a pinning/root bypass is not itself a vulnerability. A crash or failed hook is inconclusive. OS sandbox and scoped-storage rules vary by version.", cleanup: "Remove hooks, test apps, test certificates, copied data and proxy settings; restore the original build and device snapshot.", tools: ["Platform SDK tools", "Device logs", "Version-matched debugger (when needed)"] },
  storage: { id: "mobile-storage", baseline: "Record OS/build, device lock state and acquisition privileges. Create a unique synthetic account marker through the feature named below and collect a read-only snapshot of the relevant file/store before and after that action.", variation: "Locate the marker in the named store, then repeat after logout or device lock as applicable. Test access using the lowest-privilege actor in the threat model and compare against a non-sensitive control file/store.", evidence: "Store path/key, data-protection/accessibility attributes, caller permissions, marker lifetime and access results in both lock/session states.", limitation: "Root, debugger or authorized app access to decrypted data does not prove unencrypted disk storage or cross-app exposure. A missing command, empty backup or parsing error is not a clean verdict.", cleanup: "Delete synthetic records, protected acquisition copies and test backups after preserving redacted evidence; restore the device state.", tools: ["Read-only store viewer", "Platform file-protection / permission inspection"] },
  tls: { id: "client-transport", baseline: "Record the unmodified release build and trust store. Confirm the named network operation succeeds against the legitimate server with its valid certificate, and record the actual client/network stack used.", variation: "On an isolated test route compare that operation against an untrusted issuer, then a wrong-host certificate, one at a time. Do not install the test CA or apply hooks for certificate-validation tests. For pinning analysis separately label the trusted-CA and instrumented runs.", evidence: "Client build and trust state, certificate chain/SAN, successful valid control, failed-or-accepted invalid controls and packet/application trace of the synthetic operation.", limitation: "Traffic decrypted after trusting a proxy CA or modifying the client is expected instrumentation, not evidence of broken TLS. Proxy routing failure is not proof of certificate rejection; plaintext may use ports other than 80.", cleanup: "Restore routing/proxy configuration and trust stores; delete captures containing tokens and revoke synthetic sessions.", tools: ["Controlled TLS endpoint", "Packet capture", "Client logs"] },
  desktop: { id: "desktop-boundary", baseline: "Use a disposable VM with the release build. Record process identity, OS/runtime version and effective file/registry/IPC permissions. Exercise the particular feature below as its intended user.", variation: "Repeat the same named operation as a standard user or with one minimally changed local input. Compare a permitted control and a denied control; inspect the real service/backend effect rather than just a client UI response.", evidence: "Process token/identity, input artifact, effective ACL or IPC check, relevant trace and observed action under the lower-privilege actor.", limitation: "Same-user debugger/injection access is normally expected. Missing hardening, a writable directory, or a missing DLL alone does not prove elevated execution; identify the privileged consumer and trigger.", cleanup: "Restore the VM snapshot and remove test registry/files, processes, proxy settings and diagnostic dumps.", tools: ["Process Monitor / platform debugger", "Effective ACL inspection"] },
  chain: { id: "local-contract-invariant", baseline: "Pin compiler, dependencies, chain ID and fork block. Use a local Foundry/Hardhat test with test-only keys and no broadcast. Record balances, roles, nonces and the invariant relevant to the function below before a legitimate call.", variation: "From the same snapshot execute the specific candidate sequence below with the minimum actor-controlled variation, then a rejected control. Assert final state, not only transaction success/revert; include fees, repayment and all affected balances for economic claims.", evidence: "Reproducible local test, pinned block/compiler, actor prerequisites, call trace, state deltas and invariant assertion for baseline, candidate and negative control.", limitation: "Cheatcodes supply fixtures, not real attacker powers. Prove how a real actor obtains each role, signature, callback, asset and ordering assumption. Example ABI names must match the actual deployment; a scanner flag is not an exploit.", cleanup: "Discard local snapshots and test keys. No live-chain writes, approvals, mainnet funding or broadcasts are part of this method.", tools: ["Foundry or Hardhat local tests", "Verified source and ABI"] },
  directory: { id: "directory-policy", baseline: "Record the authorized lab domain/DC, OS patch level, test principal and effective policy. Query only the named object/service with read-only native tooling; compare the result to the intended permissions.", variation: "Compare the same named query/operation with an authorized principal and the unprivileged or anonymous control, holding transport and target constant. Validate ACLs and protocol requirements before isolated-lab reproduction of delegation, certificate or relay behavior.", evidence: "Target and transport, principal/SID, object ACL and effective policy, timestamped query result and related DC/service events.", limitation: "Reconnaissance and graph edges are not proven privilege escalation. Anonymous rootDSE disclosure is normal; LDAP anonymous authorization, signing and TLS channel binding are separate controls. Optional SMB signing needs NTLM availability, a relayable authentication source and target authorization before relay impact follows.", cleanup: "Remove only test objects/certificates/tickets you created, stop collectors/listeners and protect directory exports; never clear event logs.", tools: ["RSAT / native directory queries", "Effective Group Policy", "DC and service event logs"] },
  forensic: { id: "forensic-corroboration", baseline: "Work on hashed read-only copies of the named logs, capture or host artifact. Record source host, collection window, timezone, parser version and collection gaps; identify a known-benign event of the same type.", variation: "Apply the item-specific filter below to a bounded time range. Compare candidate fields and chronology with the benign control and correlate an independent source by host, account, process GUID or network tuple. Do not run suspected binaries to validate them.", evidence: "Acquisition hash, event ID/record ID or packet/frame/offset, time normalization, filter, correlated second source and confidence/gaps.", limitation: "Indicators are leads: periodic traffic/entropy does not prove C2 or exfiltration. Shimcache/Amcache alone do not prove execution; missing artifacts may reflect retention or collection gaps. Separate presence, execution, malicious intent and data transfer claims.", cleanup: "Preserve original evidence and chain of custody. Remove only analyst-generated working files under the retention policy; do not alter source logs or systems.", tools: ["Offline event/artifact parser", "Wireshark / tshark for capture items"] },
  ai: { id: "ai-trust-boundary", baseline: "Use synthetic tenant data and a mock/no-op tool sink. Record model/version, system configuration, retrieval corpus, actor permissions and sampling settings. Run the intended task with benign input and retain output plus tool/retrieval traces.", variation: "Change only the prompt, retrieved document or tool field specified in this item using a unique harmless marker. Run the same task with the marker treated as ordinary quoted data as a negative control; repeat for nondeterminism and inspect actual backend/tool effects.", evidence: "Exact prompt/document diff, role and tenant context, model settings, repeated outputs, retrieved document IDs and tool authorization/result traces.", limitation: "A model claiming success, revealing a non-secret prompt, or echoing an injected instruction is not proof of unauthorized data access or execution. Judge the specific trust-boundary outcome, including server-side authorization.", cleanup: "Remove test documents and markers, reset conversation/index state and discard synthetic sessions; keep tool sinks mocked.", tools: ["Application evaluation harness", "Retrieval and tool audit traces"] },
  cloud: { id: "cloud-identity-resource", baseline: "Record provider, region, exact owned resource and current policy/version. Use read-only configuration and audit-log inspection under a known authorized identity; prepare a synthetic resource for behavior tests.", variation: "Apply the item-specific check to that resource, comparing an intended identity with a denied test identity or one policy/input variation in a sandbox. Verify effective permissions and resource contents rather than inferring impact from names or status codes.", evidence: "Resource ID, redacted effective policy, actor identity, baseline/denied operation and provider audit event/request ID.", limitation: "A public endpoint, exposed metadata name, or tool finding is not itself sensitive access. Account for inherited policy, workload identity and organization restrictions.", cleanup: "Restore sandbox policies, remove test resources/artifacts and revoke temporary credentials; preserve audit logs.", tools: ["Provider read-only CLI / console", "Provider audit logs"] },
  protocol: { id: "item-protocol", baseline: "Identify the exact interface, protocol, input and security property in this item. Save one valid transaction or artifact with synthetic data and known expected behavior using the native client for that protocol.", variation: "Apply only the item-specific variation below to the captured valid input. Compare unchanged and rejected controls, holding identity, state and transport constant. Observe the actual parser, resource or state change, not status/length alone.", evidence: "Exact baseline and changed input, principal and preconditions, raw output/trace, protected resource state and negative control.", limitation: "Do not substitute SQL, HTTP, DNS or shell syntax for a different protocol. Samples may require target-specific names and version adaptation; one failed probe does not establish security.", cleanup: "Restore initial test state and remove synthetic objects, listeners and sessions; retain redacted evidence.", tools: ["Native protocol client", "Application trace / state inspection"] },
};
const defaults: Record<Domain, string> = { web: "protocol", api: "protocol", cloud: "cloud", ai: "ai", android: "mobile", ios: "mobile", thick_client: "desktop", web3: "chain", network_ad: "directory", binary_re: "artifact", soc_forensics: "forensic" };
// Explicit IDs only. New/custom categories keep a conservative domain strategy.
const categoryStrategies: Partial<Record<Domain, Record<string, string>>> = {
  web: {
    "recon-subdomain": "discovery", "recon-ports": "discovery", "recon-tech": "discovery", "recon-content": "discovery", "recon-params": "discovery", "recon-js": "artifact", "recon-osint": "discovery", "recon-email": "discovery", "recon-dns": "discovery",
    "auth-password": "access", "auth-session": "access", "auth-oauth": "access", "auth-login": "access", "access-idor": "access", "access-privesc": "access", "access-traversal": "parser",
    "inject-sqli": "parser", "inject-xss": "browser", "inject-ssrf": "protocol", "inject-ssti": "parser", "inject-cmd": "parser", "inject-nosql": "parser", "inject-ldap": "parser", "inject-xxe": "parser", "inject-crlf": "parser", "inject-redirect": "browser", "inject-protopoll": "parser", "inject-hpp": "parser", "inject-mail": "parser",
    "biz-logic": "access", "biz-race": "protocol", "req-csrf": "browser", "req-cors": "browser", "req-clickjacking": "browser", "req-postmessage": "browser", "client-storage": "browser", "client-resource": "browser", "file-upload": "parser", "file-download": "access", "crypto-tls": "protocol", "crypto-impl": "protocol", "config-server": "artifact", "config-cloud": "cloud", "data-exposure": "protocol", "error-handling": "protocol", "waf-bypass": "parser", "adv-smuggling": "protocol", "adv-cache": "protocol", "adv-deserialization": "parser", "adv-jwt": "access", "adv-microservices": "protocol", "adv-ssi": "parser", "adv-websocket": "protocol", "adv-graphql": "protocol", "web-framework-review": "artifact", "web-nextjs-rsc": "protocol", "web-http2-http3": "protocol", "web-modern-auth": "access",
  },
  api: { "api-recon": "discovery", "api-auth": "access", "api-injection": "parser", "api-ratelimit": "protocol", "api-rest": "protocol", "api-soap": "protocol", "api-grpc": "protocol", "api-webhook": "protocol", "api-misconfig": "protocol", "api-bopla": "access", "api-graphql-modern": "protocol" },
  cloud: { "cloud-metadata": "cloud", "cloud-storage": "cloud", "cloud-cicd": "cloud", "cloud-k8s": "cloud", "cloud-dangling": "cloud" },
  android: { "android-static": "artifact", "android-dynamic": "mobile", "android-storage": "storage", "android-crypto": "mobile", "android-network": "tls", "android-ipc": "mobile", "android-reverse": "mobile", "android-hybrid": "artifact", "android-modern-auth": "mobile" },
  ios: { "ios-static": "artifact", "ios-dynamic": "mobile", "ios-storage": "storage", "ios-network": "tls", "ios-crypto": "mobile", "ios-jailbreak": "mobile", "ios-modern-ipc": "mobile" },
  thick_client: { "tc-static": "artifact", "tc-dynamic": "desktop", "tc-binary": "desktop", "tc-network": "desktop", "tc-electron": "desktop", "tc-java": "desktop", "tc-privesc": "desktop", "tc-tauri": "desktop", "tc-proto-rce": "desktop" },
  binary_re: { "bin-mitigations": "artifact", "bin-privesc-linux": "desktop", "bin-privesc-win": "desktop", "bin-rev-eng": "artifact" },
  network_ad: { "ad-recon-enum": "directory", "ad-kerberos": "directory", "ad-net-mitm": "directory", "ad-pki-cs": "directory" },
  soc_forensics: { "soc-event-logs": "forensic", "soc-pcap-traffic": "forensic", "soc-host-artifacts": "forensic" },
  web3: { "web3-contract": "chain", "web3-access": "chain", "web3-defi": "chain", "web3-wallet": "chain", "web3-bridge": "chain", "web3-frontend": "protocol", "web3-erc4337": "chain" },
  ai: { "ai-prompt-inject": "ai", "ai-output-handling": "ai", "ai-rag-leakage": "ai", "ai-agency": "ai", "ai-dos": "ai" },
};
const itemStrategies: Record<string, string> = { "android-network-4": "protocol", "ios-dynamic-7": "protocol", "tc-network-5": "protocol", "tc-network-1": "tls", "tc-network-3": "tls", "tc-network-4": "tls", "android-crypto-5": "tls", "android-dynamic-1": "tls", "ios-dynamic-1": "tls" };
export function resolvePlaybookStrategy(domain: Domain, categoryId: string) {
  const match = categoryStrategies[domain]?.[categoryId];
  return { ...strategies[match ?? defaults[domain] ?? "protocol"], categoryMatched: !!match };
}
export function resolveItemPlaybookStrategy(item: ChecklistItem, category: ChecklistCategory, domain: Domain) {
  if (item.isCustom || category.isCustom) return resolvePlaybookStrategy(domain, "");
  const override = itemStrategies[item.id];
  return override ? { ...strategies[override], categoryMatched: true } : resolvePlaybookStrategy(domain, category.id);
}
export function createItemMethod(item: ChecklistItem, category: ChecklistCategory, domain: Domain, reviewed = false): TestingMethod {
  const strategy = resolveItemPlaybookStrategy(item, category, domain);
  return {
    id: `${item.id}:controlled-review`, title: `Controlled review: ${item.text}`, scenario: `${category.name} · ${item.id}`, verification: reviewed ? "reviewed" : "needs_adaptation",
    prerequisites: ["Identify the exact authorized asset and a disposable/synthetic fixture. Replace sample paths, identifiers and API names with values observed in that fixture.", "Record tool/runtime versions and ensure the valid control works before interpreting a failed variation."],
    tools: item.recommendedTools?.length ? item.recommendedTools : strategy.tools,
    steps: [strategy.baseline, `Item procedure: ${item.how}`, strategy.variation, ...(item.payloadNotes?.map((note, i) => `Example ${i + 1} context (see paired sample): ${note}`) ?? []), "Compare with this item's expected results below. Record confirmed, not reproduced, or inconclusive with the tested scope; tool/setup failures remain inconclusive.", strategy.cleanup],
    payloads: item.payloads,
    expectedResponse: item.expectedResponse ?? { vulnerable: `A reproducible violation of the intended security property for “${item.text}”, with actor-controlled cause and concrete effect. Define the exact invariant before running this custom check.`, safe: "The tested control is enforced for the recorded input and preconditions only. Untested paths remain unverified." },
    evidence: [strategy.evidence], limitations: [strategy.limitation, "Source-reviewed guidance is not lab verification. Commands, hooks and example ABIs must be adapted to the actual build; no sample output is an observed result."],
    safety: ["Start with read-only inspection and minimum synthetic input. Keep destructive, flooding, credential relay and state-changing sequences inside an isolated authorized lab.", strategy.cleanup],
    references: [item.reference ?? category.reference].filter((value): value is string => !!value),
  };
}
